apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-proxy-api
  namespace: vpn-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vpn-proxy-api
  template:
    metadata:
      labels:
        app: vpn-proxy-api
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: api
        image: ghcr.io/a14a-org/domeinenlijst-vpn-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: vpn-proxy-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: DB_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vpn-proxy-api-hpa
  namespace: vpn-proxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpn-proxy-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80