# Example secret file with placeholders
# DO NOT commit this file with real credentials to version control
# 
# To create the secret with actual values:
# kubectl create secret generic vpn-credentials \
#   --from-literal=SURFSHARK_USERNAME='your_username' \
#   --from-literal=SURFSHARK_PASSWORD='your_password' \
#   --from-literal=NORDVPN_USERNAME='your_username' \
#   --from-literal=NORDVPN_PASSWORD='your_password' \
#   --from-literal=NAMECHEAP_USERNAME='your_username' \
#   --from-literal=NAMECHEAP_PASSWORD='your_password' \
#   --from-literal=DB_PASSWORD='secure_db_password' \
#   -n vpn-proxy
#
apiVersion: v1
kind: Secret
metadata:
  name: vpn-credentials
  namespace: vpn-proxy
type: Opaque
stringData:
  # Replace these with your actual VPN credentials
  SURFSHARK_USERNAME: "REPLACE_WITH_ACTUAL_USERNAME"
  SURFSHARK_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  NORDVPN_USERNAME: "REPLACE_WITH_ACTUAL_USERNAME"
  NORDVPN_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  NAMECHEAP_USERNAME: "REPLACE_WITH_ACTUAL_USERNAME"
  NAMECHEAP_PASSWORD: "REPLACE_WITH_ACTUAL_PASSWORD"
  DB_PASSWORD: "REPLACE_WITH_SECURE_PASSWORD"